// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNGnmy6WnfkijzNU83oTqwccgr6f0rYY',
    appId: '1:291467756660:web:54624279c5e29abc327d21',
    messagingSenderId: '291467756660',
    projectId: 'registro-de-visitas-60b34',
    authDomain: 'registro-de-visitas-60b34.firebaseapp.com',
    storageBucket: 'registro-de-visitas-60b34.appspot.com',
    measurementId: 'G-KPJHPLTS34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZzTBLbm42CjSkc7m9u2EqiNrdmTBRTU',
    appId: '1:291467756660:android:367670f7afbc3add327d21',
    messagingSenderId: '291467756660',
    projectId: 'registro-de-visitas-60b34',
    storageBucket: 'registro-de-visitas-60b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBy3jmfpVQjQWh_Lu7uN1-CqootYoRe20',
    appId: '1:291467756660:ios:76be1d1e604f95e2327d21',
    messagingSenderId: '291467756660',
    projectId: 'registro-de-visitas-60b34',
    storageBucket: 'registro-de-visitas-60b34.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBy3jmfpVQjQWh_Lu7uN1-CqootYoRe20',
    appId: '1:291467756660:ios:76be1d1e604f95e2327d21',
    messagingSenderId: '291467756660',
    projectId: 'registro-de-visitas-60b34',
    storageBucket: 'registro-de-visitas-60b34.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaNGnmy6WnfkijzNU83oTqwccgr6f0rYY',
    appId: '1:291467756660:web:0a90e01d0daaa532327d21',
    messagingSenderId: '291467756660',
    projectId: 'registro-de-visitas-60b34',
    authDomain: 'registro-de-visitas-60b34.firebaseapp.com',
    storageBucket: 'registro-de-visitas-60b34.appspot.com',
    measurementId: 'G-QEWT7XG37L',
  );

}